### ISSUE TITLE
Termux:Float crash

### ISSUE THREAD

**Issue by discojc** [termux/termux-float#43]
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2022-05-12 00:13:38.983 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2022-05-11 21:25:51.856 UTC`  

**Crash Message**:
```
Unable to start service com.termux.window.TermuxFloatService@f24e969 with Intent { cmp=com.termux.window/.TermuxFloatService }: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.termux.window/.TermuxFloatPermissionActivity } from ProcessRecord{b0caade 29296:com.termux.window/u0a11} (pid=29296, uid=10011) with launchDisplayId=8
```

### Stacktrace

```
java.lang.RuntimeException: Unable to start service com.termux.window.TermuxFloatService@f24e969 with Intent { cmp=com.termux.window/.TermuxFloatService }: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.termux.window/.TermuxFloatPermissionActivity } from ProcessRecord{b0caade 29296:com.termux.window/u0a11} (pid=29296, uid=10011) with launchDisplayId=8
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
	at android.app.ActivityThread.access$2100(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.termux.window/.TermuxFloatPermissionActivity } from ProcessRecord{b0caade 29296:com.termux.window/u0a11} (pid=29296, uid=10011) with launchDisplayId=8
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
	at android.os.Parcel.createException(Parcel.java:2421)
	at android.os.Parcel.readException(Parcel.java:2404)
	at android.os.Parcel.readException(Parcel.java:2346)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2897)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1743)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1135)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1106)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:420)
	at com.termux.window.TermuxFloatService.initializeFloatView(TermuxFloatService.java:191)
	at com.termux.window.TermuxFloatService.onStartCommand(TermuxFloatService.java:55)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.SafeActivityOptions.checkPermissions(SafeActivityOptions.java:249)
	at com.android.server.wm.SafeActivityOptions.getOptions(SafeActivityOptions.java:132)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1307)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:891)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1872)


```
##

## Termux:Float App Info (Current)

**APP_NAME**: `Termux:Float`  
**PACKAGE_NAME**: `com.termux.window`  
**VERSION_NAME**: `0.15.0`  
**VERSION_CODE**: `15`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.19.87-24017124`  
**SDK_INT**: `31`  
**RELEASE**: `12`  
**ID**: `SP1A.210812.016`  
**DISPLAY**: `SP1A.210812.016.A716BXXU6DVD5`  
**INCREMENTAL**: `A716BXXU6DVD5`  
**SECURITY_PATCH**: `2022-04-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-A716B`  
**PRODUCT**: `a71xnsxx`  
**BOARD**: `exynos980`  
**HARDWARE**: `exynos980`  
**DEVICE**: `a71x`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by elesonnehemia-create** [comment]
Unable to start service com.termux.window.TermuxFloatService@f24e969 with Intent { cmp=com.termux.window/.TermuxFloatService }: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.termux.window/.TermuxFloatPermissionActivity } from ProcessRecord{b0caade 29296:com.termux.window/u0a11} (pid=29296, uid=10011) with launchDisplayId=8
