### ISSUE TITLE
Termux:Float app crash

### ISSUE THREAD

**Issue by Agent0fChaos** [termux/termux-float#49]
## Report Info

**User Action**: `crash report`  
**Sender**: `TermuxActivity`  
**Report Timestamp**: `2023-02-11 20:31:15.281 UTC`  
##

## Crash Details

**Crash Thread**: `Thread[main,5,main]`  
**Crash Timestamp**: `2023-02-11 20:29:08.396 UTC`  

**Crash Message**:
```
Unable to start service com.termux.window.TermuxFloatService@a364268 with Intent { cmp=com.termux.window/.TermuxFloatService }: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.termux.window/.TermuxFloatPermissionActivity } from ProcessRecord{109f0b6 30161:com.termux.window/u0a601} (pid=30161, uid=10601) with launchDisplayId=7
```

### Stacktrace

```
java.lang.RuntimeException: Unable to start service com.termux.window.TermuxFloatService@a364268 with Intent { cmp=com.termux.window/.TermuxFloatService }: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.termux.window/.TermuxFloatPermissionActivity } from ProcessRecord{109f0b6 30161:com.termux.window/u0a601} (pid=30161, uid=10601) with launchDisplayId=7
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5248)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2444)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.termux.window/.TermuxFloatPermissionActivity } from ProcessRecord{109f0b6 30161:com.termux.window/u0a601} (pid=30161, uid=10601) with launchDisplayId=7
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2774)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1801)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1145)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1116)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:441)
	at com.termux.window.TermuxFloatService.initializeFloatView(TermuxFloatService.java:191)
	at com.termux.window.TermuxFloatService.onStartCommand(TermuxFloatService.java:55)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5230)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.SafeActivityOptions.checkPermissions(SafeActivityOptions.java:286)
	at com.android.server.wm.SafeActivityOptions.getOptions(SafeActivityOptions.java:169)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1353)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:1004)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1936)


```
##

## Termux:Float App Info (Current)

**APP_NAME**: `Termux:Float`  
**PACKAGE_NAME**: `com.termux.window`  
**VERSION_NAME**: `0.15.0`  
**VERSION_CODE**: `15`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `5.10.81-android12-9-25490797-abS906USQS2BWA2`  
**SDK_INT**: `33`  
**RELEASE**: `13`  
**ID**: `TP1A.220624.014`  
**DISPLAY**: `TP1A.220624.014.S906USQS2BWA2`  
**INCREMENTAL**: `S906USQS2BWA2`  
**SECURITY_PATCH**: `2023-01-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`

**Comment by agnostic-apollo** [comment]
Try granting `Draw Over Apps` permission to Termux:Float app.

https://github.com/termux/termux-tasker#draw-over-apps-permission-optional

https://github.com/termux/termux-float/blob/e7a62c146d79938ce3849183104d00249056fe18/app/src/main/java/com/termux/window/TermuxFloatService.java#L185-L195

https://cs.android.com/android/platform/superproject/+/android-13.0.0_r31:frameworks/base/services/core/java/com/android/server/wm/SafeActivityOptions.java;l=262

https://cs.android.com/android/platform/superproject/+/android-13.0.0_r31:frameworks/base/services/core/java/com/android/server/wm/ActivityTaskSupervisor.java;l=1138
